export enum PathUrl {
  Home = "/",
  MyZiphap = "/",
  Login = "/",
  Logout = "/logout",
  Other = "/other",
  History = "/history",
  AddEvent = "/add-event",
  AddGroup = "/add-group",
  AddName = "/add-name",
  Comment = "/comment",
  Bar = "/bar",
  Map = "/map",
  AddFestival = "/add-festival",
}
